# Java Maven CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
    - checkout
    - run: mvn compile


  test:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run: mvn test


  deployment:
    machine:
      services:
      - docker

    steps:
      - run:
          name: Heroku deploy
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$APP_NAME.git master

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deployment:
          requires:
            - test
