# Java Maven CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
    - checkout
    - run: mvn compile


  test:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run: mvn test


  deployment:
    machine:
      services:
      - docker

    steps:
      - run: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$_APP_NAME.git master
#      - run: docker login -u $HEROKU_LOGIN -p $HEROKU_API_KEY registry.heroku.com
#      - run: docker build registry.heroku.com/$APP_NAME/web
#      - run: docker push registry.heroku.com/$APP_NAME/web:latest

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deployment:
          requires:
            - test
