# Java Maven CircleCI 2.0 configuration file

jobs:
  build:
    steps:
    - checkout
    - run:
        name: Maven Compile
        command: mvn compile

  test:
    steps:
      - checkout
      - run:
          name: Test
          command: mvn test

  deploy:
    steps:
      - name: Heroku
      - command: dpl --provider=heroku --app=ajc4617-simplewebapp --api-key=${HerokuID}


workflows:
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy
